# Generated by Django 5.0.4 on 2024-05-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='resume',
            field=models.FileField(null=True, upload_to='resume_folder'),
        ),
    ]
